# Uncomment the next line to define a global platform for your project
 platform :ios, '11.1'

target 'FHU Reserve' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FHU Reserve
  pod 'JBDatePicker'
  pod 'Alamofire'
  pod 'Moya-ObjectMapper'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'AlamofireImage'
end
